### PR TITLE
Create PR template

### PR DESCRIPTION
**Pull request by jossjohnson-sealabs**
Creating new Pull Request template

### CODE REVIEW

**Comment by jeanvega-sealabs** [comment]
@jossjohnson-sealabs please change the base to DEV

**Comment by jeanvega-sealabs** [comment]
@jossjohnson-sealabs  file's route should be "./github"

**Review by jeanvega-sealabs — CHANGES_REQUESTED** [review]
check my comments

**Comment by jossjohnson-sealabs** [comment]
Pull Request is update @jeanvega-sealabs

**Review by jeanvega-sealabs — APPROVED** [review]

**Pull request merged**
